#!/usr/bin/env python3
"""
B2: 生成3份免费研究报告并输出发布材料

用法:
  python scripts/b2_research_reports.py [--api-url https://www.nautilus.social]

输出:
  reports/report_1_ai_agent_economy.md
  reports/report_2_claude_code_architecture.md
  reports/report_3_proof_of_useful_work.md
  reports/social_posts.md   ← 各平台发帖文案
"""
import argparse
import asyncio
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path

try:
    import aiohttp
except ImportError:
    print("缺少 aiohttp，正在安装...")
    os.system(f"{sys.executable} -m pip install aiohttp -q")
    import aiohttp


API_URL = os.getenv("NAUTILUS_API_URL", "https://www.nautilus.social")

REPORTS = [
    {
        "slug": "ai_agent_economy",
        "topic": (
            "AI Agent Economy 2025: How Networks of Self-Improving Agents Are "
            "Reshaping Knowledge Work. Analyze: (1) economic models for AI agent "
            "compensation (task-based vs subscription), (2) proof-of-useful-work "
            "as a replacement for proof-of-work, (3) real-world examples of agents "
            "generating measurable economic value, (4) the role of reputation and "
            "survival mechanisms in maintaining quality, (5) predictions for 2026."
        ),
        "depth": "thorough",
        "title": "AI Agent Economy 2025: Networks of Self-Improving Agents Are Reshaping Knowledge Work",
        "reddit_community": "r/artificial",
        "twitter_hook": "AI agents are about to change how knowledge work gets compensated forever.",
        "zhihu_tag": "AI经济、Agent经济学",
    },
    {
        "slug": "claude_code_architecture",
        "topic": (
            "Claude Code Multi-Agent Architecture: A Technical Deep Dive. Analyze: "
            "(1) how Claude Code uses KAIROS time-budget mechanism for task scheduling, "
            "(2) the autoDream memory consolidation pattern and how it resembles human sleep, "
            "(3) Swarm orchestration for parallel agent coordination, "
            "(4) how tool plugins extend agent capabilities without retraining, "
            "(5) lessons developers can apply to build their own multi-agent systems."
        ),
        "depth": "standard",
        "title": "Claude Code's Hidden Architecture: KAIROS, autoDream, and Multi-Agent Orchestration Patterns",
        "reddit_community": "r/ClaudeAI",
        "twitter_hook": "Claude Code has a surprisingly sophisticated internal architecture — here's what we found.",
        "zhihu_tag": "Claude、AI编程助手、多智能体",
    },
    {
        "slug": "proof_of_useful_work",
        "topic": (
            "Proof-of-Useful-Work (PoUW): The Economic Layer Missing from AI Agent Ecosystems. "
            "Cover: (1) why traditional PoW wastes compute while PoUW creates value, "
            "(2) how NAU token design aligns agent incentives with platform health, "
            "(3) the survival mechanism — why agents that don't create value should be deprecated, "
            "(4) technical implementation: on-chain minting linked to verifiable task completion, "
            "(5) comparison with existing compute markets (Akash, Render, etc.)."
        ),
        "depth": "standard",
        "title": "Proof-of-Useful-Work: The Economic Model That Makes AI Agents Accountable",
        "reddit_community": "r/ethereum",
        "twitter_hook": "What if every crypto token minted required an AI agent to complete a real task?",
        "zhihu_tag": "区块链、AI、PoUW代币经济学",
    },
]

NAUTILUS_BRAND_FOOTER = """

---

*This report was synthesized by [Nautilus](https://www.nautilus.social) — a decentralized AI agent ecosystem where agents earn, evolve, and compete on real tasks.*

*Want your own deep research report? Message [@openclaw_cxchat_bot](https://t.me/openclaw_cxchat_bot) on Telegram.*
"""


def _banner(topic_title: str) -> str:
    return f"""# {topic_title}

*Generated by Nautilus DeerFlow Research Pipeline · {datetime.now().strftime("%B %Y")}*

---

"""


def _social_post(report: dict, gdoc_url: str | None) -> str:
    link = gdoc_url or f"https://www.nautilus.social/blog"
    return f"""
### {report['title']}

**Twitter/X** ({report['twitter_hook']}):
```
{report['twitter_hook']}

Full research report 👇
{link}

Powered by @NautilusSocial AI agent network
#AI #AgentEconomy #Web4
```

**Reddit ({report['reddit_community']})**:
> Title: {report['title']}
> Link: {link}
> [OC] Generated via Nautilus multi-agent research pipeline

**知乎** (标签: {report['zhihu_tag']}):
> 标题: {report['title']}
> 本报告由 Nautilus 去中心化 AI Agent 网络的 DeerFlow 研究管线生成。
> 原文: {link}
"""


async def generate_report(session: aiohttp.ClientSession, report: dict) -> tuple[str, dict]:
    """Call DeerFlow API and return (markdown_content, raw_result)."""
    url = f"{API_URL}/api/research/deep"
    payload = {
        "topic": report["topic"],
        "depth": report["depth"],
        "save_to_gdoc": False,
    }

    print(f"\n  POST {url}")
    print(f"  depth={report['depth']}, topic={report['topic'][:60]}...")

    start = time.time()

    # All depths now return job_id immediately — poll for result
    async with session.post(url, json=payload, timeout=aiohttp.ClientTimeout(total=30)) as resp:
        resp.raise_for_status()
        data = await resp.json()

    job_id = data.get("data", {}).get("job_id")
    if not job_id:
        raise ValueError(f"No job_id in response: {data}")

    print(f"  Job {job_id} submitted, polling...")
    status_url = f"{API_URL}/api/research/status/{job_id}"
    result = {}
    for _ in range(60):  # up to ~15 min
        await asyncio.sleep(15)
        async with session.get(status_url, timeout=aiohttp.ClientTimeout(total=10)) as sresp:
            sresp.raise_for_status()
            sdata = await sresp.json()
        status = sdata.get("data", {}).get("status")
        print(f"  status={status} ({int(time.time()-start)}s elapsed)")
        if status == "completed":
            result = sdata["data"].get("result", sdata["data"])
            break
        if status == "failed":
            raise RuntimeError(f"Research job failed: {sdata.get('error')}")

    elapsed = time.time() - start
    report_text = result.get("report", "")
    gdoc_url = result.get("gdoc_url")
    print(f"  Done in {elapsed:.0f}s — {len(report_text)} chars")
    return report_text, result


async def main(api_url: str) -> None:
    global API_URL
    API_URL = api_url

    output_dir = Path(__file__).parent / "reports"
    output_dir.mkdir(exist_ok=True)

    social_posts = []
    connector = aiohttp.TCPConnector(ssl=True)

    async with aiohttp.ClientSession(connector=connector) as session:
        for i, report in enumerate(REPORTS, 1):
            slug = report["slug"]
            print(f"\n[{i}/{len(REPORTS)}] Generating: {report['title']}")

            try:
                report_text, raw = await generate_report(session, report)
            except Exception as e:
                print(f"  ERROR: {e}")
                report_text = f"[Generation failed: {e}]"
                raw = {}

            # Write markdown file
            md_path = output_dir / f"report_{i}_{slug}.md"
            with open(md_path, "w", encoding="utf-8") as f:
                f.write(_banner(report["title"]))
                f.write(report_text)
                f.write(NAUTILUS_BRAND_FOOTER)
            print(f"  Saved: {md_path}")

            # Save raw JSON
            json_path = output_dir / f"report_{i}_{slug}_raw.json"
            with open(json_path, "w", encoding="utf-8") as f:
                json.dump({"report_meta": report, "result": raw}, f, ensure_ascii=False, indent=2)

            social_posts.append(_social_post(report, raw.get("gdoc_url")))

    # Write social posts file
    posts_path = output_dir / "social_posts.md"
    with open(posts_path, "w", encoding="utf-8") as f:
        f.write("# Nautilus Research Reports — Social Media Posts\n\n")
        f.write(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n\n---\n")
        f.write("\n---\n".join(social_posts))
    print(f"\nSocial posts saved: {posts_path}")

    print("\n=== All reports generated ===")
    print(f"Output directory: {output_dir.resolve()}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Nautilus research reports via DeerFlow API")
    parser.add_argument(
        "--api-url",
        default=os.getenv("NAUTILUS_API_URL", "https://www.nautilus.social"),
        help="Nautilus API base URL (default: https://www.nautilus.social)",
    )
    args = parser.parse_args()
    asyncio.run(main(args.api_url))
