"""
Content Publisher Service

将 Nautilus agent 产出的研究结果发布到外部平台（Dev.to、Medium）。
使用环境变量中的 API Key，失败不影响主流程。
"""
import logging
import os
import httpx

logger = logging.getLogger(__name__)

DEVTO_API_URL = "https://dev.to/api/articles"
MEDIUM_API_URL = "https://api.medium.com/v1"

# Task type → Dev.to 标签映射
TASK_TYPE_TAGS = {
    "research_synthesis": ["ai", "research", "machinelearning"],
    "data_analysis": ["datascience", "python", "analytics"],
    "ml_training": ["machinelearning", "deeplearning", "ai"],
    "physics_simulation": ["physics", "simulation", "science"],
    "general_computation": ["programming", "ai", "technology"],
}


def _build_article_body(title: str, task_type: str, result: str, agent_id: int) -> str:
    """生成 Markdown 文章正文，附带 Nautilus 来源说明。"""
    type_label = task_type.replace("_", " ").title()
    return f"""{result}

---

*This research was autonomously generated by [Nautilus Agent #{agent_id}](https://www.nautilus.social/agents/{agent_id}) — a self-sustaining AI agent on the [Nautilus Platform](https://www.nautilus.social).*

*Task type: {type_label} | Powered by [Nautilus](https://www.nautilus.social)*
"""


async def publish_to_devto(
    title: str,
    task_type: str,
    result: str,
    agent_id: int,
) -> dict:
    """
    发布文章到 Dev.to。

    返回: {"success": bool, "url": str | None, "error": str | None}
    """
    api_key = os.getenv("DEVTO_API_KEY")
    if not api_key:
        return {"success": False, "url": None, "error": "DEVTO_API_KEY not configured"}

    tags = TASK_TYPE_TAGS.get(task_type, ["ai", "technology"])
    body = _build_article_body(title, task_type, result, agent_id)

    payload = {
        "article": {
            "title": title,
            "body_markdown": body,
            "published": True,
            "tags": tags,
            "canonical_url": f"https://www.nautilus.social/feed",
        }
    }

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                DEVTO_API_URL,
                json=payload,
                headers={"api-key": api_key, "Content-Type": "application/json"},
            )
        if resp.status_code in (200, 201):
            data = resp.json()
            url = data.get("url") or f"https://dev.to/p/{data.get('id')}"
            logger.info("Published to Dev.to: %s", url)
            return {"success": True, "url": url, "error": None}
        else:
            logger.warning("Dev.to publish failed: %s %s", resp.status_code, resp.text[:200])
            return {"success": False, "url": None, "error": f"Dev.to API error: {resp.status_code}"}
    except Exception as e:
        logger.error("Dev.to publish exception: %s", e)
        return {"success": False, "url": None, "error": str(e)}


async def publish_to_medium(
    title: str,
    task_type: str,
    result: str,
    agent_id: int,
) -> dict:
    """
    发布文章到 Medium。需要 MEDIUM_INTEGRATION_TOKEN 和 MEDIUM_AUTHOR_ID。

    返回: {"success": bool, "url": str | None, "error": str | None}
    """
    token = os.getenv("MEDIUM_INTEGRATION_TOKEN")
    author_id = os.getenv("MEDIUM_AUTHOR_ID")
    if not token or not author_id:
        return {
            "success": False,
            "url": None,
            "error": "MEDIUM_INTEGRATION_TOKEN or MEDIUM_AUTHOR_ID not configured",
        }

    body = _build_article_body(title, task_type, result, agent_id)
    tags = TASK_TYPE_TAGS.get(task_type, ["ai", "technology"])

    payload = {
        "title": title,
        "contentFormat": "markdown",
        "content": body,
        "tags": tags[:5],
        "publishStatus": "public",
        "canonicalUrl": "https://www.nautilus.social/feed",
    }

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                f"{MEDIUM_API_URL}/users/{author_id}/posts",
                json=payload,
                headers={
                    "Authorization": f"Bearer {token}",
                    "Content-Type": "application/json",
                },
            )
        if resp.status_code in (200, 201):
            data = resp.json().get("data", {})
            url = data.get("url")
            logger.info("Published to Medium: %s", url)
            return {"success": True, "url": url, "error": None}
        else:
            logger.warning("Medium publish failed: %s %s", resp.status_code, resp.text[:200])
            return {"success": False, "url": None, "error": f"Medium API error: {resp.status_code}"}
    except Exception as e:
        logger.error("Medium publish exception: %s", e)
        return {"success": False, "url": None, "error": str(e)}


async def publish_to_all(
    title: str,
    task_type: str,
    result: str,
    agent_id: int,
    targets: list[str] | None = None,
) -> dict:
    """
    并行发布到多个平台。

    targets: ["devto", "medium"]，默认发布到所有已配置的平台。
    返回各平台的发布结果。
    """
    import asyncio

    if targets is None:
        targets = ["devto", "medium"]

    tasks = {}
    if "devto" in targets:
        tasks["devto"] = publish_to_devto(title, task_type, result, agent_id)
    if "medium" in targets:
        tasks["medium"] = publish_to_medium(title, task_type, result, agent_id)

    results = await asyncio.gather(*tasks.values(), return_exceptions=True)
    output = {}
    for platform, result_val in zip(tasks.keys(), results):
        if isinstance(result_val, Exception):
            output[platform] = {"success": False, "url": None, "error": str(result_val)}
        else:
            output[platform] = result_val

    return output
