"""
PDF generation service for Nautilus research deliverables.

Converts DeerFlow research output and academic task results to PDF.
Uses reportlab (lightweight, pure Python) as primary backend.
Falls back to plain text if reportlab not available.

Install: pip install reportlab
"""
import io
import logging
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)


def generate_research_pdf(
    title: str,
    topic: str,
    sections: dict,
    task_id: str,
    agent_name: str = "Nautilus Agent",
    nau_earned: float = 0,
) -> bytes:
    """
    Generate a PDF research report from DeerFlow sections.

    Args:
        title: Report title
        topic: Original research topic
        sections: DeerFlow sections dict with keys: summary, findings, recommendations
        task_id: Academic task ID (for footer reference)
        agent_name: Name of agent that produced the report
        nau_earned: NAU tokens earned for this task

    Returns:
        PDF as bytes
    """
    try:
        return _generate_with_reportlab(title, topic, sections, task_id, agent_name, nau_earned)
    except ImportError:
        logger.warning("reportlab not installed, generating plain text fallback")
        return _generate_plain_text(title, topic, sections, task_id).encode("utf-8")


def _generate_with_reportlab(
    title: str,
    topic: str,
    sections: dict,
    task_id: str,
    agent_name: str,
    nau_earned: float,
) -> bytes:
    """Generate PDF using reportlab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2.5 * cm,
        rightMargin=2.5 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=18,
        spaceAfter=12,
        textColor=colors.HexColor("#1a1a2e"),
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=13,
        spaceBefore=16,
        spaceAfter=8,
        textColor=colors.HexColor("#16213e"),
    )
    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=16,
        spaceAfter=8,
    )
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.grey,
    )

    story = []

    # Header
    story.append(Paragraph("NAUTILUS RESEARCH REPORT", meta_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph(title, title_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#6c63ff")))
    story.append(Spacer(1, 8))

    # Metadata table
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    meta_data = [
        ["Generated", now],
        ["Task ID", task_id],
        ["Agent", agent_name],
        ["NAU Earned", f"{nau_earned:.0f} NAU" if nau_earned else "Pending"],
        ["Pipeline", "DeerFlow Multi-Agent"],
    ]
    meta_table = Table(meta_data, colWidths=[3 * cm, 12 * cm])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 16))

    # Topic
    story.append(Paragraph("Research Topic", heading_style))
    story.append(Paragraph(topic, body_style))

    # Sections
    section_map = {
        "summary": "Executive Summary",
        "findings": "Key Findings",
        "recommendations": "Recommendations",
    }
    for key, heading in section_map.items():
        content = sections.get(key, "")
        if content:
            story.append(Paragraph(heading, heading_style))
            for para in content.split("\n\n"):
                if para.strip():
                    story.append(Paragraph(para.strip(), body_style))

    # Footer
    story.append(Spacer(1, 24))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        f"Generated by Nautilus Platform · Proof of Useful Work · "
        f"Task {task_id} · {now}",
        meta_style
    ))

    doc.build(story)
    return buffer.getvalue()


def _generate_plain_text(title: str, topic: str, sections: dict, task_id: str) -> str:
    """Plain text fallback when reportlab is unavailable."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "NAUTILUS RESEARCH REPORT",
        "=" * 60,
        f"Title: {title}",
        f"Generated: {now}",
        f"Task ID: {task_id}",
        "",
        "RESEARCH TOPIC",
        "-" * 40,
        topic,
        "",
    ]
    for key, heading in [
        ("summary", "EXECUTIVE SUMMARY"),
        ("findings", "KEY FINDINGS"),
        ("recommendations", "RECOMMENDATIONS"),
    ]:
        content = sections.get(key, "")
        if content:
            lines += [heading, "-" * 40, content, ""]

    lines.append(f"--- Nautilus Platform · Task {task_id} ---")
    return "\n".join(lines)


def pdf_from_academic_task(task_data: dict) -> Optional[bytes]:
    """
    Generate PDF from an academic task dict (from /api/academic-tasks/{id}).

    Returns PDF bytes or None if task has no output.
    """
    if task_data.get("status") != "completed":
        return None

    params = {}
    try:
        import json
        raw = task_data.get("parameters", "{}")
        params = json.loads(raw) if isinstance(raw, str) else (raw or {})
    except Exception:
        pass

    deerflow = params.get("_deerflow", {})
    sections = deerflow.get("sections") or {
        "summary": task_data.get("result_output", ""),
        "findings": "",
        "recommendations": "",
    }

    return generate_research_pdf(
        title=task_data.get("title", "Research Report"),
        topic=task_data.get("description", ""),
        sections=sections,
        task_id=task_data.get("task_id", "unknown"),
        nau_earned=task_data.get("token_reward", 0) or 0,
    )
