"""
File Upload API — token-gated file/image upload for chat users.

Security:
- Upload requires a one-time token (generated by bot, 15 min expiry)
- Upload page without valid token shows "request link from bot" message
- Served files use Content-Disposition: attachment (no inline execution)
- Executable extensions blocked
- Per-IP rate limiting (20 uploads/hour)
- Path traversal prevention
"""
import hashlib
import logging
import os
import secrets
import time
import uuid
from collections import defaultdict
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, File, Form, UploadFile, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse

logger = logging.getLogger(__name__)

router = APIRouter()

UPLOAD_DIR = Path(os.getenv("UPLOAD_DIR", "/home/ubuntu/nautilus-mvp/uploads"))
MAX_FILE_SIZE = 20 * 1024 * 1024  # 20MB
ALLOWED_EXTENSIONS = {
    ".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp",  # images
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",  # docs
    ".csv", ".txt", ".md", ".json",  # text
    ".py", ".m", ".mat", ".inp", ".dat",  # code/data
}
BLOCKED_EXTENSIONS = {
    ".exe", ".bat", ".cmd", ".com", ".msi", ".scr", ".pif",
    ".js", ".vbs", ".wsf", ".ps1", ".sh", ".bash",
    ".dll", ".sys", ".drv", ".bin", ".elf",
    ".php", ".jsp", ".asp", ".aspx", ".cgi",
    ".html", ".htm", ".svg",  # prevent stored XSS
}
BASE_URL = os.getenv("BASE_URL", "https://www.nautilus.social")
TOKEN_EXPIRY = 900  # 15 minutes
RATE_LIMIT_PER_HOUR = 20

# Token store: token -> {"user_id": str, "created_at": float}
_tokens: dict = {}
# Rate limit: ip -> [timestamps]
_upload_counts: dict = defaultdict(list)


def _ensure_upload_dir():
    UPLOAD_DIR.mkdir(parents=True, exist_ok=True)


def generate_upload_token(user_id: str) -> str:
    """Generate a one-time upload token for a user. Called by bot handlers."""
    _cleanup_expired_tokens()
    token = secrets.token_urlsafe(24)
    _tokens[token] = {"user_id": user_id, "created_at": time.time()}
    return token


def _cleanup_expired_tokens():
    now = time.time()
    expired = [t for t, v in _tokens.items() if now - v["created_at"] > TOKEN_EXPIRY]
    for t in expired:
        del _tokens[t]


def _validate_token(token: str) -> Optional[str]:
    """Validate token. Returns user_id if valid, None otherwise."""
    _cleanup_expired_tokens()
    info = _tokens.get(token)
    if not info:
        return None
    return info["user_id"]


def _check_rate_limit(ip: str) -> bool:
    """Returns True if under rate limit."""
    now = time.time()
    hour_ago = now - 3600
    _upload_counts[ip] = [t for t in _upload_counts[ip] if t > hour_ago]
    return len(_upload_counts[ip]) < RATE_LIMIT_PER_HOUR


def _record_upload(ip: str):
    _upload_counts[ip].append(time.time())


@router.get("", response_class=HTMLResponse)
async def upload_page(token: Optional[str] = None):
    """Serve the file upload HTML page."""
    valid_user = _validate_token(token) if token else None
    return HTMLResponse(content=_build_html(token or "", valid_user))


@router.post("")
async def upload_file(
    request: Request,
    file: UploadFile = File(...),
    token: str = Form(""),
    note: Optional[str] = Form(None),
):
    """Accept a file upload. Requires valid token."""
    # Validate token
    user_id = _validate_token(token)
    if not user_id:
        raise HTTPException(403, "上传链接已过期或无效。请在对话中发送任意文件，获取新的上传链接。")

    # Rate limit
    client_ip = request.client.host if request.client else "unknown"
    if not _check_rate_limit(client_ip):
        raise HTTPException(429, "上传过于频繁，请稍后再试。")

    _ensure_upload_dir()

    # Validate extension
    original_name = file.filename or "unknown"
    ext = Path(original_name).suffix.lower()
    if ext in BLOCKED_EXTENSIONS:
        raise HTTPException(400, f"安全原因，不允许上传 {ext} 类型文件。")
    if ext not in ALLOWED_EXTENSIONS:
        raise HTTPException(400, f"不支持的文件类型 {ext}。支持: {', '.join(sorted(ALLOWED_EXTENSIONS))}")

    # Validate content
    content = await file.read()
    if len(content) > MAX_FILE_SIZE:
        raise HTTPException(400, f"文件过大。最大 {MAX_FILE_SIZE // 1024 // 1024}MB")
    if len(content) == 0:
        raise HTTPException(400, "文件为空")

    # Generate safe filename (no user-controlled characters in path)
    file_id = uuid.uuid4().hex[:12]
    safe_name = f"{file_id}{ext}"
    file_path = UPLOAD_DIR / safe_name
    file_path.write_bytes(content)

    _record_upload(client_ip)

    # Consume token (one-time use)
    _tokens.pop(token, None)

    download_url = f"{BASE_URL}/api/upload/files/{safe_name}"

    # Save metadata
    meta_path = UPLOAD_DIR / f"{file_id}.meta.txt"
    meta_path.write_text(
        f"original_name: {original_name}\n"
        f"size: {len(content)}\n"
        f"user_id: {user_id}\n"
        f"note: {note or ''}\n"
        f"uploaded_at: {time.strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"ip: {client_ip}\n"
        f"url: {download_url}\n",
        encoding="utf-8",
    )

    logger.info("File uploaded: %s (%s, %d bytes) user=%s ip=%s", original_name, ext, len(content), user_id, client_ip)

    return {
        "success": True,
        "file_id": file_id,
        "filename": original_name,
        "size": len(content),
        "url": download_url,
        "message": "文件已上传成功！回到对话告诉小鹦即可。",
    }


@router.get("/files/{filename}")
async def serve_file(filename: str):
    """Serve an uploaded file with attachment disposition (no inline execution)."""
    _ensure_upload_dir()
    # Sanitize filename
    safe = Path(filename).name  # strip any path components
    file_path = UPLOAD_DIR / safe
    if not file_path.exists() or not file_path.is_file():
        raise HTTPException(404, "File not found")
    if not file_path.resolve().is_relative_to(UPLOAD_DIR.resolve()):
        raise HTTPException(403, "Access denied")

    return FileResponse(
        file_path,
        filename=safe,
        # Force download, never inline-render in browser
        headers={"Content-Disposition": f'attachment; filename="{safe}"'},
    )


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

def _build_html(token: str, valid_user: Optional[str]) -> str:
    if not valid_user:
        return _EXPIRED_HTML
    return UPLOAD_HTML.replace("__TOKEN__", token)


_EXPIRED_HTML = """<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Nautilus - 上传链接已过期</title>
<style>
body { font-family: -apple-system, sans-serif; background: #0a0e17; color: #e0e0e0;
       display: flex; justify-content: center; align-items: center; min-height: 100vh; }
.box { text-align: center; max-width: 400px; padding: 40px; }
h1 { color: #ff6b6b; font-size: 1.3rem; }
p { color: #999; margin-top: 12px; line-height: 1.6; }
</style></head><body>
<div class="box">
<h1>上传链接已过期或无效</h1>
<p>请在企微/Telegram 对话中发送任意文件或图片，<br>系统会自动生成新的上传链接。</p>
</div></body></html>"""


UPLOAD_HTML = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Nautilus - 文件上传</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       background: #0a0e17; color: #e0e0e0; min-height: 100vh;
       display: flex; flex-direction: column; align-items: center; padding: 20px; }
h1 { color: #00d4ff; margin: 20px 0 8px; font-size: 1.5rem; }
.subtitle { color: #888; margin-bottom: 24px; font-size: 0.9rem; }
.drop-zone { width: 100%; max-width: 500px; min-height: 200px;
             border: 2px dashed #333; border-radius: 12px;
             display: flex; flex-direction: column; align-items: center;
             justify-content: center; padding: 24px; cursor: pointer;
             transition: all 0.3s; background: #111827; }
.drop-zone:hover, .drop-zone.dragover { border-color: #00d4ff; background: #0d1b2a; }
.drop-zone p { color: #999; margin: 8px 0; }
.drop-zone .icon { font-size: 2.5rem; margin-bottom: 8px; }
input[type="file"] { display: none; }
.note-input { width: 100%; max-width: 500px; margin-top: 12px; padding: 10px 14px;
              background: #111827; border: 1px solid #333; border-radius: 8px;
              color: #e0e0e0; font-size: 0.9rem; }
.note-input::placeholder { color: #666; }
.btn { background: #00d4ff; color: #000; border: none; padding: 10px 24px;
       border-radius: 8px; font-size: 1rem; cursor: pointer; margin-top: 12px;
       font-weight: 600; transition: background 0.2s; }
.btn:hover { background: #00b8d4; }
.btn:disabled { background: #333; color: #666; cursor: not-allowed; }
.result { width: 100%; max-width: 500px; margin-top: 16px; padding: 16px;
          background: #111827; border-radius: 8px; display: none; }
.result.success { border-left: 4px solid #00d4ff; }
.result.error { border-left: 4px solid #ff4444; }
.file-list { width: 100%; max-width: 500px; margin-top: 8px; }
.file-item { background: #1a2332; padding: 8px 12px; border-radius: 6px;
             margin-top: 6px; display: flex; justify-content: space-between;
             font-size: 0.85rem; }
.file-item .name { color: #ccc; flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.file-item .size { color: #888; margin-left: 12px; }
.progress { height: 3px; background: #333; border-radius: 2px; margin-top: 8px;
            width: 100%; max-width: 500px; overflow: hidden; display: none; }
.progress-bar { height: 100%; background: #00d4ff; width: 0%; transition: width 0.3s; }
.security { color: #666; font-size: 0.75rem; margin-top: 16px; max-width: 500px; text-align: center; }
</style>
</head>
<body>
<h1>Nautilus 文件上传</h1>
<p class="subtitle">上传后回到对话告诉小鹦即可</p>

<div class="drop-zone" id="dropZone">
  <div class="icon">📁</div>
  <p>拖拽文件到这里，或点击选择</p>
  <p style="font-size:0.8rem; color:#666;">图片、PDF、文档、数据文件 (最大20MB)</p>
</div>
<input type="file" id="fileInput" multiple>

<div class="file-list" id="fileList"></div>
<input class="note-input" id="noteInput" placeholder="备注（可选）：描述文件内容">
<div class="progress" id="progress"><div class="progress-bar" id="progressBar"></div></div>
<button class="btn" id="uploadBtn" disabled>上传</button>
<div class="result" id="result"></div>
<p class="security">链接15分钟内有效，仅限一次上传</p>

<script>
const TOKEN = "__TOKEN__";
const dropZone = document.getElementById('dropZone');
const fileInput = document.getElementById('fileInput');
const fileList = document.getElementById('fileList');
const uploadBtn = document.getElementById('uploadBtn');
const result = document.getElementById('result');
const progress = document.getElementById('progress');
const progressBar = document.getElementById('progressBar');
const noteInput = document.getElementById('noteInput');
let selectedFiles = [];

dropZone.addEventListener('click', () => fileInput.click());
dropZone.addEventListener('dragover', e => { e.preventDefault(); dropZone.classList.add('dragover'); });
dropZone.addEventListener('dragleave', () => dropZone.classList.remove('dragover'));
dropZone.addEventListener('drop', e => {
  e.preventDefault(); dropZone.classList.remove('dragover');
  addFiles(e.dataTransfer.files);
});
fileInput.addEventListener('change', () => addFiles(fileInput.files));

function addFiles(files) {
  for (const f of files) selectedFiles.push(f);
  renderFileList();
  uploadBtn.disabled = selectedFiles.length === 0;
}
function renderFileList() {
  fileList.innerHTML = selectedFiles.map(f =>
    '<div class="file-item"><span class="name">'+f.name+'</span><span class="size">'+(f.size/1024).toFixed(0)+'KB</span></div>'
  ).join('');
}

uploadBtn.addEventListener('click', async () => {
  if (!selectedFiles.length) return;
  uploadBtn.disabled = true; uploadBtn.textContent = '上传中...';
  progress.style.display = 'block'; result.style.display = 'none';

  const results = [];
  for (let i = 0; i < selectedFiles.length; i++) {
    progressBar.style.width = ((i+0.5)/selectedFiles.length*100)+'%';
    const fd = new FormData();
    fd.append('file', selectedFiles[i]);
    fd.append('token', TOKEN);
    fd.append('note', noteInput.value);
    try {
      const resp = await fetch('/api/upload', {method:'POST', body:fd});
      results.push(await resp.json());
    } catch(e) {
      results.push({success:false, message:e.message, filename:selectedFiles[i].name});
    }
    progressBar.style.width = ((i+1)/selectedFiles.length*100)+'%';
  }

  const ok = results.filter(r=>r.success), fail = results.filter(r=>!r.success);
  let html = '';
  if (ok.length) {
    html += '<p style="color:#00d4ff;margin-bottom:8px;">'+ok.length+' 个文件上传成功</p>';
    ok.forEach(r => { html += '<p style="margin:4px 0;">'+r.filename+' ('+r.url+')</p>'; });
    html += '<p style="margin-top:12px;color:#aaa;">回到对话告诉小鹦即可。</p>';
  }
  if (fail.length) {
    html += '<p style="color:#ff4444;margin-top:8px;">'+fail.length+' 个文件失败</p>';
    fail.forEach(r => { html += '<p style="color:#ff8888;">'+(r.filename||'')+': '+(r.message||r.detail||'error')+'</p>'; });
  }
  result.innerHTML = html;
  result.style.display = 'block';
  result.className = 'result '+(fail.length?'error':'success');
  selectedFiles = []; renderFileList();
  uploadBtn.textContent = '上传'; uploadBtn.disabled = true;
  setTimeout(() => { progress.style.display='none'; progressBar.style.width='0%'; }, 1000);
});
</script>
</body>
</html>"""
