#!/bin/bash
# 监控系统部署 - 快速完成脚本

echo "=== Nautilus 监控系统部署完成指南 ==="
echo ""
echo "当前状态："
echo "✅ Prometheus 运行中 (端口 9090)"
echo "✅ Grafana 运行中 (端口 3001)"
echo "✅ AlertManager 运行中 (端口 9093)"
echo "✅ Node Exporter 运行中 (端口 9100)"
echo "✅ API 端点代码已上传"
echo ""
echo "需要完成的步骤："
echo ""
echo "1. 启动后端服务"
echo "   ssh cloud 'cd /home/ubuntu/nautilus-mvp/phase3/monitoring && bash deploy-backend.sh'"
echo ""
echo "2. 验证监控端点"
echo "   curl http://43.160.239.61:9090/-/healthy"
echo "   curl http://43.160.239.61:3001/api/health"
echo "   curl http://43.160.239.61:9093/-/healthy"
echo "   curl http://43.160.239.61:8000/metrics"
echo "   curl http://43.160.239.61:8000/api/alerts/health"
echo ""
echo "3. 测试告警规则"
echo "   ssh cloud 'cd /home/ubuntu/nautilus-mvp/phase3/monitoring && bash alert-test.sh'"
echo ""
echo "4. 提交代码"
echo "   cd /c/Users/chunx/Projects/nautilus-core/phase3/backend"
echo "   git add api/metrics.py api/alerts.py main.py"
echo "   git commit -m 'feat: 部署监控系统到生产环境"
echo ""
echo "   - 部署 Prometheus + Grafana + Loki + AlertManager"
echo "   - 实现 /metrics 端点"
echo "   - 实现告警 webhook 端点"
echo "   - 配置 Grafana 仪表板"
echo "   - 测试告警规则"
echo ""
echo "   Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>'"
echo "   git push origin master"
echo ""
echo "访问地址："
echo "- Prometheus: http://43.160.239.61:9090"
echo "- Grafana: http://43.160.239.61:3001 (admin/admin123)"
echo "- AlertManager: http://43.160.239.61:9093"
echo ""
